english_words_correct = {
    "Car": "Bil",
    "Dog": "Hund",
    "Cat": "Katt",
    "House": "Hus",
    "Table": "Bord",
    "Computer": "Dator",
    "Phone": "Telefon",
    "Tree": "Träd",
    "Happy": "Glad",
    "Sad": "Ledsen",
    "Run": "Springa",
    "Walk": "Gå",
    "Jump": "Hoppa",
    "Laugh": "Skratta",
    "Cry": "Gråta",
    "Swim": "Simma",
    "Fly": "Flyga",
    "Bird": "Fågel",
    "Flower": "Blomma",
    "River": "Flod",
    "Mountain": "Berg",
    "Beach": "Strand",
    "Ocean": "Hav",
    "Book": "Bok",
    "Pen": "Penna",
    "Pencil": "Blyertspenna",
    "School": "Skola",
    "Student": "Elev",
    "Teacher": "Lärare",
    "Doctor": "Läkare",
    "Nurse": "Sjuksköterska",
    "Dentist": "Tandläkare",
    "Lawyer": "Advokat",
    "Police": "Polis",
    "Fire": "Eld",
    "Sun": "Sol",
    "Moon": "Måne",
    "Star": "Stjärna",
    "Sky": "Himmel",
    "Cloud": "Moln",
    "Rain": "Regn",
    "Snow": "Snö",
    "Wind": "Vind",
    "Hot": "Varm",
    "Cold": "Kall",
    "Big": "Stor",
    "Small": "Liten",
    "Fast": "Snabb",
    "Slow": "Långsam",
    "High": "Hög",
    "Low": "Låg",
    "Difficult": "Svår",
    "Easy": "Lätt",
    "Expensive": "Dyr",
    "Cheap": "Billig",
    "Clean": "Ren",
    "Dirty": "Smutsig",
    "Bright": "Ljus",
    "Dark": "Mörk",
    "Tasty": "God",
    "Bland": "Smaklös",
    "Quiet": "Tyst",
    "Noisy": "Bullrig",
    "Busy": "Upptagen",
    "Calm": "Lugn",
    "Angry": "Arg",
    "Kind": "Snäll",
    "Mean": "Elak",
    "Soft": "Mjuk",
    "Hard": "Hård",
    "Old": "Gammal",
    "New": "Ny",
    "Modern": "Modern",
    "Ancient": "Forntida",
    "Brave": "Modig",
    "Coward": "Fegis",
    "Honest": "Ärlig",
    "Dishonest": "Ohederlig",
    "Wise": "Vis",
    "Foolish": "Dum",
    "Friend": "Vän",
    "Enemy": "Fiende",
    "Love": "Kärlek",
    "Hate": "Hat",
    "Peace": "Fred",
    "War": "Krig",
    "Success": "Framgång",
    "Failure": "Misslyckande",
    "Health": "Hälsa",
    "Illness": "Sjukdom",
    "Hungry": "Hungrig",
    "Full": "Mätt",
    "Thirsty": "Törstig",
    "Dry": "Torr"
}

english_words_easy = [
    "Bil",
    "Hund",
    "Katt",
    "Hus",
    "Bord",
    "Dator",
    "Telefon",
    "Träd",
    "Glad",
    "Ledsen",
    "Springa",
    "Gå",
    "Hoppa",
    "Skratta",
    "Gråta",
    "Simma",
    "Flyga",
    "Fågel",
    "Blomma",
    "Flod",
    "Berg",
    "Strand",
    "Hav",
    "Bok",
    "Penna",
    "Blyertspenna",
    "Skola",
    "Elev",
    "Lärare",
    "Läkare",
    "Sjuksköterska",
    "Tandläkare",
    "Advokat",
    "Polis",
    "Eld",
    "Sol",
    "Måne",
    "Stjärna",
    "Himmel",
    "Moln",
    "Regn",
    "Snö",
    "Vind",
    "Varm",
    "Kall",
    "Stor",
    "Liten",
    "Snabb",
    "Långsam",
    "Hög",
    "Låg",
    "Svår",
    "Lätt",
    "Dyr",
    "Billig",
    "Ren",
    "Smutsig",
    "Ljus",
    "Mörk",
    "God",
    "Smaklös",
    "Tyst",
    "Bullrig",
    "Upptagen",
    "Lugn",
    "Arg",
    "Snäll",
    "Elak",
    "Mjuk",
    "Hård",
    "Gammal",
    "Ny",
    "Modern",
    "Forntida",
    "Modig",
    "Fegis",
    "Ärlig",
    "Ohederlig",
    "Vis",
    "Dum",
    "Vän",
    "Fiende",
    "Kärlek",
    "Hat",
    "Fred",
    "Krig",
    "Framgång",
    "Misslyckande",
    "Hälsa",
    "Sjukdom",
    "Hungrig",
    "Mätt",
    "Törstig",
    "Torr"
]